"""Build report & Drive-link emails — shared HTML templates with consistent branding."""

from __future__ import annotations

from collections.abc import Iterable
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from datetime import datetime
from email import encoders
from pathlib import Path
from html import escape
import smtplib
import os

from core.constants import (
    REPORT_BODY_OPEN, REPORT_BODY_CLOSE, REPORT_BORDER_LR,
    APP_TITLE, APP_VERSION, LOGS_DIR, StepResult,
    REPORT_SECTION_H2, REPORT_TH_STYLE,
    REPORT_ACCENT, REPORT_CARD_BORDER, REPORT_CARD_BG,
    REPORT_BG, REPORT_SUCCESS, REPORT_ERROR, REPORT_MUTED,
    REPORT_SECTION,
)

from helpers.types import LogFn, fmt_elapsed


# ── Shared HTML fragments ────────────────────────────────────────────────────


def _html_header(subtitle: str) -> str:
    return (
        f'<div style="background:linear-gradient(135deg,#0284c7,{REPORT_ACCENT});'
        'border-radius:12px 12px 0 0;padding:22px 20px;text-align:center;">'
        '<h1 style="margin:0;font-size:22px;color:#fff;letter-spacing:-0.3px;">'
        f"⚡ {escape(APP_TITLE)}</h1>"
        '<p style="margin:4px 0 0;font-size:13px;color:rgba(255,255,255,0.8);font-weight:500;">'
        f"{subtitle}</p></div>"
    )


def _html_footer() -> str:
    return (
        f'<div style="background:{REPORT_CARD_BG};border-radius:0 0 12px 12px;'
        f'{REPORT_BORDER_LR}border-bottom:1px solid {REPORT_CARD_BORDER};padding:14px 20px;text-align:center;">'
        f'<p style="margin:0 0 2px;font-size:10px;color:#475569;">'
        f'Generated by <strong style="color:{REPORT_ACCENT};">{escape(APP_TITLE)}</strong>'
        f" v{escape(APP_VERSION)}</p>"
        '<p style="margin:0;font-size:10px;color:#334155;">'
        "Made with ❤️ by Senpai</p></div>"
    )


def _html_banner(text: str, bg: str) -> str:
    return (
        f'<div style="background:{bg};padding:9px 20px;text-align:center;">'
        f'<span style="color:#020617;font-size:14px;font-weight:700;'
        f'letter-spacing:0.2px;">{text}</span></div>'
    )


def _summary_row(label: str, value: str, *, color: str = "#e2e8f0", bold: bool = False) -> str:
    weight = "font-weight:600;" if bold else ""
    return (
        f'<tr><td style="padding:4px 0;color:#64748b;font-size:12px;width:100px;">'
        f"{escape(label)}</td>"
        f'<td style="padding:4px 0;color:{color};font-size:13px;{weight}">'
        f"{escape(value)}</td></tr>"
    )


def _section_card_open() -> str:
    return f'<div style="background:{REPORT_CARD_BG};{REPORT_BORDER_LR}">'


def _section_heading(title: str) -> str:
    return (
        f'<div style="padding:12px 20px 6px;border-top:1px solid {REPORT_CARD_BORDER};">'
        f"<h2 {REPORT_SECTION_H2}>{title}</h2></div>"
    )


# ── Helpers ──────────────────────────────────────────────────────────────────

def _get_primary_recipient() -> str | None:
    raw = os.environ.get("DISTRIBUTION_EMAILS", "").strip()
    if not raw:
        return None
    first = raw.split(",")[0].strip()
    return first if "@" in first else None


def _gmail_credentials() -> tuple[str, str] | None:
    user = os.environ.get("GMAIL_USER", "").strip()
    pw = os.environ.get("GMAIL_APP_PASSWORD", "").strip()
    return (user, pw) if user and pw else None


def _send_html_email(
    *,
    subject: str,
    html: str,
    recipients: list[str],
    gmail_user: str,
    gmail_pass: str,
    attachment_path: Path | None = None,
) -> None:
    if attachment_path:
        msg = MIMEMultipart("mixed")
        msg.attach(MIMEText(html, "html", "utf-8"))
        part = MIMEBase("application", "octet-stream")
        part.set_payload(attachment_path.read_bytes())
        encoders.encode_base64(part)
        part.add_header("Content-Disposition", "attachment", filename=attachment_path.name)
        msg.attach(part)
    else:
        msg = MIMEMultipart("alternative")
        msg.attach(MIMEText(html, "html", "utf-8"))

    msg["Subject"] = subject
    msg["From"] = gmail_user
    msg["To"] = ", ".join(recipients)

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(gmail_user, gmail_pass)
        server.sendmail(gmail_user, recipients, msg.as_string())


def _status_badge(ok: bool) -> str:
    if ok:
        return (
            '<span style="display:inline-block;background:#065f46;color:#34d399;'
            'padding:1px 8px;border-radius:20px;font-size:11px;font-weight:600;">'
            "✓ Passed</span>"
        )
    return (
        '<span style="display:inline-block;background:#7f1d1d;color:#fca5a5;'
        'padding:1px 8px;border-radius:20px;font-size:11px;font-weight:600;">'
        "✗ Failed</span>"
    )


def save_log(lines: Iterable[str], version: str, build: str) -> Path:
    """Write pipeline log under ``logs/``; return the file path."""
    LOGS_DIR.mkdir(exist_ok=True)
    ts = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    name = f"build_v{version}+{build}_{ts}.txt" if version else f"build_{ts}.txt"
    path = LOGS_DIR / name
    with path.open("w", encoding="utf-8") as f:
        for line in lines:
            f.write(line)
    return path


# ── Build Report HTML ────────────────────────────────────────────────────────

def _build_report_html(
    *,
    version: str,
    build: str,
    platforms: str,
    total_elapsed: str,
    success: bool,
    step_results: list[StepResult],
) -> str:
    status_color = REPORT_SUCCESS if success else REPORT_ERROR
    status_text = "Build Succeeded" if success else "Build Failed"
    status_emoji = "✓" if success else "✗"

    step_rows = ""
    for name, ok, elapsed in step_results:
        step_rows += (
            "<tr>"
            f'<td style="padding:7px 12px;border-bottom:1px solid {REPORT_CARD_BORDER};'
            f'color:#e2e8f0;font-size:13px;">{escape(name)}</td>'
            f'<td style="padding:7px 12px;border-bottom:1px solid {REPORT_CARD_BORDER};'
            f'text-align:center;">{_status_badge(ok)}</td>'
            f'<td style="padding:7px 12px;border-bottom:1px solid {REPORT_CARD_BORDER};'
            f'color:{REPORT_SECTION};font-size:12px;text-align:right;'
            f'font-family:Consolas,monospace;">{fmt_elapsed(elapsed)}</td>'
            "</tr>"
        )

    now_str = datetime.now().strftime("%b %d, %Y — %I:%M %p")

    return (
        f"{REPORT_BODY_OPEN}"
        f'{_html_header(f"Build Report &mdash; v{escape(version)}+{escape(build)}")}'
        f"{_html_banner(f'{status_emoji}&ensp;{status_text}', status_color)}"

        f'<div style="background:{REPORT_CARD_BG};padding:16px 20px;{REPORT_BORDER_LR}">'
        '<table style="width:100%;border-collapse:collapse;">'
        f'{_summary_row("Version", f"v{version}+{build}", bold=True)}'
        f'{_summary_row("Platforms", platforms)}'
        f'{_summary_row("Total Time", total_elapsed, color=REPORT_ACCENT, bold=True)}'
        f'{_summary_row("Date", now_str)}'
        "</table></div>"

        f"{_section_card_open()}"
        f'{_section_heading("Pipeline Steps")}'
        '<table style="width:100%;border-collapse:collapse;">'
        f'<tr style="background:{REPORT_BG};">'
        f'{REPORT_TH_STYLE.format(align="left").join(["<th ", ">Step</th>"])}'
        f'{REPORT_TH_STYLE.format(align="center").join(["<th ", ">Status</th>"])}'
        f'{REPORT_TH_STYLE.format(align="right").join(["<th ", ">Time</th>"])}'
        f"</tr>{step_rows}</table></div>"

        f"{_html_footer()}"
        f"{REPORT_BODY_CLOSE}"
    )


# ── Drive Link HTML ──────────────────────────────────────────────────────────

def build_drive_link_html(
    *,
    link: str,
    label: str,
    file_names: list[str],
    version: str = "",
    build: str = "",
) -> str:
    """Branded HTML email for a Drive upload notification."""
    version_tag = f"v{escape(version)}+{escape(build)}" if version and build else ""
    subtitle = f"{escape(label)} Upload"
    if version_tag:
        subtitle += f" &mdash; {version_tag}"

    file_rows = ""
    for fname in file_names:
        file_rows += (
            f'<tr><td style="padding:6px 12px;border-bottom:1px solid {REPORT_CARD_BORDER};'
            f'color:#e2e8f0;font-size:13px;">📦&ensp;{escape(fname)}</td></tr>'
        )

    now_str = datetime.now().strftime("%b %d, %Y — %I:%M %p")

    return (
        f"{REPORT_BODY_OPEN}"
        f"{_html_header(subtitle)}"
        f'{_html_banner("📁&ensp;Upload Complete", REPORT_SUCCESS)}'

        f'<div style="background:{REPORT_CARD_BG};padding:16px 20px;{REPORT_BORDER_LR}">'
        '<table style="width:100%;border-collapse:collapse;">'
        f'{_summary_row("Type", f"{label} Build", bold=True)}'
        + (f'{_summary_row("Version", f"v{version}+{build}", bold=True)}' if version else "")
        + f'{_summary_row("Date", now_str)}'
        "</table></div>"

        f"{_section_card_open()}"
        f'{_section_heading("Uploaded Files")}'
        '<table style="width:100%;border-collapse:collapse;">'
        f"{file_rows}</table></div>"

        f'<div style="background:{REPORT_CARD_BG};padding:18px 20px;text-align:center;{REPORT_BORDER_LR}">'
        f'<a href="{escape(link)}" style="display:inline-block;background:'
        f'linear-gradient(135deg,#0284c7,{REPORT_ACCENT});color:#fff;text-decoration:none;'
        'padding:11px 32px;border-radius:8px;font-size:14px;font-weight:700;'
        'letter-spacing:0.2px;">Open in Google Drive</a>'
        f'<p style="margin:8px 0 0;font-size:11px;color:{REPORT_MUTED};">'
        "Anyone with the link can view</p></div>"

        f"{_html_footer()}"
        f"{REPORT_BODY_CLOSE}"
    )


# ── Public API ───────────────────────────────────────────────────────────────

def send_build_report(
    *,
    log_lines: Iterable[str],
    step_results: list[StepResult],
    version: str,
    build: str,
    platforms: str,
    total_elapsed: str,
    success: bool,
    log: LogFn,
) -> None:
    """Save log file and email HTML build report to the primary recipient."""
    log_path = save_log(log_lines, version, build)
    log(f"Build log saved → {log_path}\n")

    recipient = _get_primary_recipient()
    if not recipient:
        log("No DISTRIBUTION_EMAILS configured; skipping report email.\n")
        return

    creds = _gmail_credentials()
    if not creds:
        log("Gmail credentials not configured; skipping report email.\n")
        return

    html = _build_report_html(
        version=version,
        build=build,
        platforms=platforms,
        total_elapsed=total_elapsed,
        success=success,
        step_results=step_results,
    )

    status_emoji = "✓" if success else "✗"
    subject = f"{status_emoji} {APP_TITLE} v{version}+{build} — Build Report"

    try:
        _send_html_email(
            subject=subject,
            html=html,
            recipients=[recipient],
            gmail_user=creds[0],
            gmail_pass=creds[1],
            attachment_path=log_path,
        )
        log(f"Build report emailed to {recipient}\n")
    except Exception as e:
        log(f"Failed to email build report: {e}\n")


def send_drive_link_email(
    *,
    link: str,
    label: str,
    file_names: list[str],
    recipients: list[str],
    version: str = "",
    build: str = "",
    log: LogFn,
) -> bool:
    """Send a branded HTML Drive-link email. Returns True on success."""
    creds = _gmail_credentials()
    if not creds:
        log("Gmail not configured; skipping email of Drive link.\n")
        return True

    html = build_drive_link_html(
        link=link, label=label, file_names=file_names,
        version=version, build=build,
    )

    version_tag = f" v{version}+{build}" if version and build else ""
    subject = f"📦 {label} Build Ready{version_tag} — Download Link"

    try:
        _send_html_email(
            subject=subject,
            html=html,
            recipients=recipients,
            gmail_user=creds[0],
            gmail_pass=creds[1],
        )
        log(f"  Drive link emailed to {len(recipients)} recipient(s).\n")
        return True
    except Exception as e:
        log(f"  Failed to email Drive link: {e}\n")
        return False
